# Generated by Django 3.0.6 on 2020-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('img', models.ImageField(default=None, upload_to='pics')),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(default=None, max_length=1000)),
                ('zipCode', models.IntegerField(default=0)),
                ('email', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('proCount', models.IntegerField(default=0)),
                ('selfDec', models.TextField(default=None)),
            ],
        ),
    ]
