# Generated by Django 3.0.6 on 2020-05-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_auto_20200522_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreeName', models.CharField(max_length=600)),
                ('uniName', models.CharField(max_length=600)),
                ('year', models.CharField(max_length=50)),
                ('eduDes', models.TextField()),
            ],
        ),
    ]
