# Generated by Django 3.0.6 on 2020-05-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expName', models.CharField(max_length=600)),
                ('instName', models.CharField(max_length=600)),
                ('year', models.CharField(max_length=50)),
                ('expDes', models.TextField()),
            ],
        ),
    ]
