# Generated by Django 3.0.6 on 2020-05-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardsName', models.CharField(default=None, max_length=600)),
                ('year', models.CharField(default=None, max_length=50)),
                ('awardsDes', models.TextField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='degreeName',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='education',
            name='eduDes',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='education',
            name='uniName',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='expDes',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='experience',
            name='expName',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='experience',
            name='instName',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
