# Generated by Django 3.0.6 on 2020-05-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0005_auto_20200523_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='awardsInsName',
            field=models.CharField(default=None, max_length=600),
        ),
    ]
