# Generated by Django 3.0.6 on 2020-05-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0006_awards_awardsinsname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='awardsInsName',
            field=models.CharField(default='-', max_length=600),
        ),
    ]
