# Generated by Django 3.0.6 on 2020-05-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0007_auto_20200523_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='awardsInsName',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
