# Generated by Django 3.0.6 on 2020-06-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0010_auto_20200523_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(default=None, max_length=600)),
                ('experienceYear', models.CharField(default=None, max_length=50)),
                ('reletedTechnology', models.CharField(default=None, max_length=600)),
                ('serviceDes', models.TextField(default=None)),
            ],
        )
    ]
