# Generated by Django 3.0.6 on 2020-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0011_auto_20200619_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='awardsInsName',
            field=models.CharField(default=None, max_length=600),
        ),
    ]
