# Generated by Django 3.0.6 on 2020-06-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0013_auto_20200619_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='awardsInsName',
        ),
    ]
